#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/fabrication_output"
REPORTS="$OUT/reports"
POWER="$ROOT/docs/boards/PowerBoard"
LOGIC="$ROOT/docs/boards/LogicBoard"

mkdir -p "$REPORTS" "$OUT/PowerBoard/gerbers" "$OUT/LogicBoard/gerbers"

if ! command -v kicad-cli >/dev/null 2>&1; then
  echo "ERROR: kicad-cli not found" >&2
  exit 127
fi

kicad-cli --version | tee "$REPORTS/kicad_cli_version.txt"

# ERC. These commands are expected to fail if schematic syntax/library data is not yet acceptable to KiCad.
kicad-cli sch erc --output "$REPORTS/PowerBoard_erc.rpt" "$POWER/PowerBoard.kicad_sch"
kicad-cli sch erc --output "$REPORTS/LogicBoard_erc.rpt" "$LOGIC/LogicBoard.kicad_sch"

# DRC.
kicad-cli pcb drc --output "$REPORTS/PowerBoard_drc.rpt" "$POWER/PowerBoard.kicad_pcb"
kicad-cli pcb drc --output "$REPORTS/LogicBoard_drc.rpt" "$LOGIC/LogicBoard.kicad_pcb"

# Gerbers and drills.
kicad-cli pcb export gerbers --output "$OUT/PowerBoard/gerbers" "$POWER/PowerBoard.kicad_pcb"
kicad-cli pcb export drill --output "$OUT/PowerBoard/gerbers" "$POWER/PowerBoard.kicad_pcb"

kicad-cli pcb export gerbers --output "$OUT/LogicBoard/gerbers" "$LOGIC/LogicBoard.kicad_pcb"
kicad-cli pcb export drill --output "$OUT/LogicBoard/gerbers" "$LOGIC/LogicBoard.kicad_pcb"

cat > "$OUT/README_FAB_OUTPUT.txt" <<'EOF'
This artifact is generated by scripts/kicad_export.sh.
Do not order blindly unless ERC/DRC reports are clean and Gerbers have been reviewed in an independent Gerber viewer.
EOF

find "$OUT" -type f | sort
